name: Node CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build --if-present
        yarn test
      env:
        CI: true
  package:
    name: Package
    needs: test
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and pack
      run: |
        yarn install
        yarn build --if-present
        yarn pack --filename discord-game.tgz
    - name: Upload Package
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: discord-game.tgz
